### ISSUE TITLE
java.lang.IllegalArgumentException · MIME type may not be blank

### ISSUE THREAD

**Issue by CAMOBAP** [wonderpush/wonderpush-android-sdk#1] opened 2018-04-09 10:06 UTC
I faced with this issue only once, for `Samsung SM-T580` Android 7.0

Unfortunately I don't know exact version of WonderPush SDK

Full stack trace is:

```
java.lang.ExceptionInInitializerError ·
UrlEncodedFormEntity.java:62c.a.a.a.b.b.a.<init>	
RequestParams.java:566com.c.a.a.r.createFormEntity	
RequestParams.java:520com.c.a.a.r.getEntity	
WonderPushRestClient.java:302com.wonderpush.sdk.WonderPushRestClient$4.run	
WonderPush.java:1357com.wonderpush.sdk.WonderPush$3.run	
Handler.java:751android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
Looper.java:154android.os.Looper.loop	
WonderPush.java:70com.wonderpush.sdk.WonderPush$1.run	
Thread.java:762java.lang.Thread.run	
Caused By: java.lang.IllegalArgumentException · MIME type may not be blank
Args.java:68c.a.a.a.o.a.b	
ContentType.java:175c.a.a.a.g.e.a	
ContentType.java:80c.a.a.a.g.e.<clinit>	
UrlEncodedFormEntity.java:62c.a.a.a.b.b.a.<init>	
RequestParams.java:566com.c.a.a.r.createFormEntity	
RequestParams.java:520com.c.a.a.r.getEntity	
WonderPushRestClient.java:302com.wonderpush.sdk.WonderPushRestClient$4.run	
WonderPush.java:1357com.wonderpush.sdk.WonderPush$3.run	
Handler.java:751android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
Looper.java:154android.os.Looper.loop	
WonderPush.java:70com.wonderpush.sdk.WonderPush$1.run	
Thread.java:762java.lang.Thread.run
```

**Comment by ofavre** [comment] 2019-02-18 14:11
Cannot reproduce.
We'll soon change the HTTP library anyways, closing this issue.
Thanks for reporting anyway.

**Closed as completed by ofavre** 2019-02-18 14:11 UTC
